In [60]:
import pandas as pd
dataset = pd.read_csv("dataset/Training.csv")

In [61]:
dataset.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [62]:
dataset.shape

(4920, 133)

In [63]:
len(dataset['prognosis'].unique())

41

In [64]:
dataset['prognosis'].unique()

<StringArray>
[                       'Fungal infection',
                                 'Allergy',
                                    'GERD',
                     'Chronic cholestasis',
                           'Drug Reaction',
                     'Peptic ulcer diseae',
                                    'AIDS',
                               'Diabetes ',
                         'Gastroenteritis',
                        'Bronchial Asthma',
                           'Hypertension ',
                                'Migraine',
                    'Cervical spondylosis',
            'Paralysis (brain hemorrhage)',
                                'Jaundice',
                                 'Malaria',
                             'Chicken pox',
                                  'Dengue',
                                 'Typhoid',
                             'hepatitis A',
                             'Hepatitis B',
                             'Hepatitis C',
                             'Hepatitis D',
                             'Hepatitis E',
                     'Alcoholic hepatitis',
                            'Tuberculosis',
                             'Common Cold',
                               'Pneumonia',
            'Dimorphic hemmorhoids(piles)',
                            'Heart attack',
                          'Varicose veins',
                          'Hypothyroidism',
                         'Hyperthyroidism',
                            'Hypoglycemia',
                         'Osteoarthristis',
                               'Arthritis',
 '(vertigo) Paroymsal  Positional Vertigo',
                                    'Acne',
                 'Urinary tract infection',
                               'Psoriasis',
                                'Impetigo']
Length: 41, dtype: str

In [65]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [66]:
x = dataset.drop("prognosis", axis=1)
y = dataset["prognosis"]

In [67]:
x

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4916,0,1,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4918,0,1,0,0,0,0,1,0,0,0,...,0,0,0,1,1,1,1,0,0,0
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1